services:
  opmsa-demo:
    build: .
    ports:
      - "4112:4111"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - dmit_network

networks:
  dmit_network:
    external: true